{% set name = "nbiatoolkit" %}
{% set version = "0.25.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nbiatoolkit-{{ version }}.tar.gz
  sha256: bd60d09d560a6df938ab5fe5999e287df3a27660124c590084fb703ba4329e80

build:
  entry_points:
    - dicomsort = nbiatoolkit.nbia_cli:DICOMSorter_cli
    - NBIAToolkit = nbiatoolkit:version
    - getCollections = nbiatoolkit.nbia_cli:getCollections_cli
    - getBodyPartCounts = nbiatoolkit.nbia_cli:getBodyPartCounts_cli
    - getPatients = nbiatoolkit.nbia_cli:getPatients_cli
    - getNewPatients = nbiatoolkit.nbia_cli:getNewPatients_cli
    - getStudies = nbiatoolkit.nbia_cli:getStudies_cli
    - getSeries = nbiatoolkit.nbia_cli:getSeries_cli
    - getNewSeries = nbiatoolkit.nbia_cli:getNewSeries_cli
    - downloadSingleSeries = nbiatoolkit.nbia_cli:downloadSingleSeries_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - poetry-core
    - pip
  run:
    - python >=3.10
    - requests 2.31.0
    - pydicom >=2.4.3,<3.0.0
    - tqdm >=4.66.1,<5.0.0
    - pyfiglet >=1.0.0,<2.0.0
    - beautifulsoup4 >=4.12.3,<5.0.0

test:
  imports:
    - nbiatoolkit
  commands:
    - pip check
    - dicomsort --help
    - NBIAToolkit --help
    - getCollections --help
    - getBodyPartCounts --help
    - getPatients --help
    - getNewPatients --help
    - getStudies --help
    - getSeries --help
    - getNewSeries --help
    - downloadSingleSeries --help
  requires:
    - pip

about:
  home: https://github.com/jjjermiah/nbia-toolkit
  summary: A python package to query the National Biomedical Imaging Archive (NBIA) database.
  license: MIT
  license_file: LICENSE
  doc_url: https://nbia-toolkit.readthedocs.io/

extra:
  recipe-maintainers:
    - jjjermiah
